#!/usr/bin/expect --
set result [spawn scp  <isDir> <verbose> <sourcePath> <userName>@<host>:<destinationPath>]
if { $result == 0 } {
	send_user "\nSCP program $scpprog failed to start!\n"
	exit 1
}
sleep 1

set timeout 15
set isgood 0

# nudge SCP along, answering "yes" and giving password
set needrepeat 1
while { $needrepeat != 0 } {
	set needrepeat 0
	expect {
		"assword" {
			sleep 1
			send "<password>\r"
			set isgood 1
		}
		"re you sure you want" {
			sleep 1
			send "yes\r"
			set needrepeat 1
		}
		timeout {
			send_user "\nSCP program $scpprog failed to connect!\n"
			exit 1
		}
	}
}

if { $isgood != 1 } {
	send_user "\nSCP failed to establish connection!\n";
	exit 1
}

set timeout 1000
set isgood 0

# wait for SCP to complete transferring the file
expect {
	"ermission denied" {
		send_user "\nSCP did not like that password!\n"
		exit 1
	}
	"100%" {
		set isgood 1
		send_user "\nComplete!\n"
	}
	timeout {
		send_user "\nSCP failed to work after giving password!\n"
		exit 1
	}
}

if { $isgood != 1 } {
	send_user "\nSCP failed during upload of the file!\n"
	exit 1
}

# see if it worked
set resultlist [wait -i $spawn_id]
set resultstatus [lindex $resultlist 2]
set resultcode [lindex $resultlist 3]
if { $resultstatus != 0 } {
	send_user "\nSystem error $resultcode while running SCP program!\n";
	exit 1
}
if { $resultcode != 0 } {
	send_user "\nError $resultcode returned by SCP program!\n";
	exit 1
}

exit 0
