#!/usr/bin/expect --
spawn scp  -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 <isDir> <verbose> <sourcePath> <userName>@<host>:<destinationPath>
expect "assword:" {send "<password>\n"}
expect "*%*" {set timeout -1}
expect eof
