//--------------------------------------------------------
// ORProXR16SSRModel
// Created by Mark  A. Howe on Thurs June 21, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark •••Imported Files
#import "ORBitProcessing.h"

@class ORSerialPort;

#define kProXR16SSRCmdStart			0xFE
#define kProXR16SSRRelayOnStart		0x64
#define kProXR16SSRRelayOffStart	0x6C
#define kProXR16SSRCmdResponse		0x55
#define kProXR16SSRAllRelayStatus	0x7C

@interface ORProXR16SSRModel : OrcaObject <ORBitProcessing>
{
@private
    NSString*       portName;
    BOOL            portWasOpen;
    ORSerialPort*   serialPort;
    unsigned long	dataId;
    NSData*			lastRequest;
    NSMutableArray* cmdQueue;
	
    BOOL			relayState[16];
	NSMutableArray* outletNames;
}

#pragma mark •••Initialization
- (id)   init;
- (void) dealloc;

- (void) registerNotificationObservers;

#pragma mark •••Accessors
- (ORSerialPort*) serialPort;
- (void) setSerialPort:(ORSerialPort*)aSerialPort;
- (BOOL) portWasOpen;
- (void) setPortWasOpen:(BOOL)aPortWasOpen;
- (NSString*) portName;
- (void) setPortName:(NSString*)aPortName;
- (void) openPort:(BOOL)state;
- (NSString*) outletName:(int)index;
- (void) setOutlet:(int)index name:(NSString*)aName;

#pragma mark •••Main Scripting Methods
- (NSString*) commonScriptMethods;
- (void) commonScriptMethodSectionBegin;
- (void) turnRelayOn:(int) index;
- (void) turnRelayOff:(int) index;
- (void) readAllRelayStates;
- (BOOL) relayState:(int) index;
- (void) commonScriptMethodSectionEnd;

#pragma mark •••Commands
- (void) addCmdToQueue:(NSData*)aCmd;
- (void) dataReceived:(NSNotification*)note;

#pragma mark •••Archival
- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;

#pragma mark •••Adc Processing Protocol
- (void) processIsStarting;
- (void) processIsStopping; 
- (void) startProcessCycle;
- (void) endProcessCycle;
- (BOOL) processValue:(int)channel;
- (void) setProcessOutput:(int)channel value:(int)value;
- (void) setOutputBit:(int)channel value:(int)value;
- (NSString*) processingTitle;

@end

extern NSString* ORProXR16SSRModelPollTimeChanged;
extern NSString* ORProXR16SSRModelSerialPortChanged;
extern NSString* ORProXR16SSRLock;
extern NSString* ORProXR16SSRModelPortNameChanged;
extern NSString* ORProXR16SSRModelPortStateChanged;
extern NSString* ORProXR16SSRModelRelayStateChanged;
extern NSString* ORProXR16SSRModelUpdateAllRelaysChanged;
extern NSString* ORProXR16SSRModelOutletNameChanged;
