//--------------------------------------------------------
// ORTPG256AModel
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
//  Created by Mark Howe on Mon Apr 16 2012.
//  Copyright 2012  University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark •••Imported Files

#import "ORTPG256AModel.h"
#import "ORSerialPort.h"
#import "ORSerialPortList.h"
#import "ORSerialPortAdditions.h"
#import "ORDataTypeAssigner.h"
#import "ORDataPacket.h"
#import "ORTimeRate.h"
#import "ORSafeQueue.h"

#pragma mark •••External Strings
NSString* ORTPG256AModelUnitsChanged = @"ORTPG256AModelUnitsChanged";
NSString* ORTPG256AModelPressureScaleChanged = @"ORTPG256AModelPressureScaleChanged";
NSString* ORTPG256AModelShipPressuresChanged = @"ORTPG256AModelShipPressuresChanged";
NSString* ORTPG256AModelPollTimeChanged		 = @"ORTPG256AModelPollTimeChanged";
NSString* ORTPG256AModelSerialPortChanged	 = @"ORTPG256AModelSerialPortChanged";
NSString* ORTPG256AModelPortNameChanged		 = @"ORTPG256AModelPortNameChanged";
NSString* ORTPG256AModelPortStateChanged	 = @"ORTPG256AModelPortStateChanged";
NSString* ORTPG256APressureChanged			 = @"ORTPG256APressureChanged";
NSString* ORTPG256AModelHighLimitChanged	 = @"ORTPG256AModelHighLimitChanged";
NSString* ORTPG256AModelHighAlarmChanged	 = @"ORTPG256AModelHighAlarmChanged";
NSString* ORTPG256AModelLowLimitChanged		 = @"ORTPG256AModelLowLimitChanged";
NSString* ORTPG256AModelLowAlarmChanged		 = @"ORTPG256AModelLowAlarmChanged";

NSString* ORTPG256ALock = @"ORTPG256ALock";

#define kACK			0x06
#define kNAK			0x15
#define kENQ			0x05
#define kEXT			0x03
#define kWaitingForACK	1
#define kProcessData	2

@interface ORTPG256AModel (private)
- (void) runStarted:(NSNotification*)aNote;
- (void) runStopped:(NSNotification*)aNote;
- (void) timeout;
- (void) processOneCommandFromQueue;
- (void) process_response:(NSString*)theResponse;
- (void) pollPressures;
@end

@implementation ORTPG256AModel
- (id) init
{
	self = [super init];
    [self registerNotificationObservers];
	int i;
	for(i=0;i<6;i++){
		lowLimit[i]  = 0; 
		highLimit[i] = 1.0; 
		lowAlarm[i]  = 0; 
		highAlarm[i] = 1.0; 
	}
	
	return self;
}

- (void) dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [NSObject cancelPreviousPerformRequestsWithTarget:self];
    [buffer release];
	[cmdQueue release];
	[lastRequest release];
    [portName release];
    if([serialPort isOpen]){
        [serialPort close];
    }
    [serialPort release];
	int i;
	for(i=0;i<6;i++){
		[timeRates[i] release];
	}

	[super dealloc];
}

- (void) wakeUp
{
    [super wakeUp];
	[self pollPressures];
}

- (void) sleep
{
    [super sleep];
	[NSObject cancelPreviousPerformRequestsWithTarget:self];
}

- (void) setUpImage
{
	[self setImage:[NSImage imageNamed:@"TPG256A.tif"]];
}

- (void) makeMainController
{
	[self linkToController:@"ORTPG256AController"];
}

- (NSString*) helpURL
{
	return @"RS232/TPG256A.html";
}

- (void) registerNotificationObservers
{
	NSNotificationCenter* notifyCenter = [NSNotificationCenter defaultCenter];

    [notifyCenter addObserver : self
                     selector : @selector(dataReceived:)
                         name : ORSerialPortDataReceived
                       object : nil];

    [notifyCenter addObserver: self
                     selector: @selector(runStarted:)
                         name: ORRunStartedNotification
                       object: nil];
    
    [notifyCenter addObserver: self
                     selector: @selector(runStopped:)
                         name: ORRunStoppedNotification
                       object: nil];

}


- (void) dataReceived:(NSNotification*)note
{
    if([[note userInfo] objectForKey:@"serialPort"] == serialPort){
        NSString* theString = [[[[NSString alloc] initWithData:[[note userInfo] objectForKey:@"data"] 
												      encoding:NSASCIIStringEncoding] autorelease] uppercaseString];

 		//the serial port may break the data up into small chunks, so we have to accumulate the chunks until
		//we get a full piece.       
		if(!buffer)buffer = [[NSMutableString string] retain];
        [buffer appendString:theString];	
		
		if([buffer hasSuffix:@"\r\n"]){
			//got a full chunk ... process according to the port data state
			if(portDataState == kWaitingForACK){
				if([buffer characterAtIndex:0] == kNAK){
					//error in transimission
					//flush and go to next command
					NSLogError(@"TGP262",@"Transmission Error",nil);
					[self setLastRequest:nil];			 //clear the last request
					[self processOneCommandFromQueue];	 //do the next command in the queue
				}
				else if([buffer characterAtIndex:0] == kACK){
					//device has sent us a positive aknowledgement of the command
					//respond with a request to transmit data and enter new state
					[serialPort writeString:[NSString stringWithFormat:@"%c",kENQ]];
					portDataState = kProcessData;
				}
			}
			else if(portDataState == kProcessData){
				//OK, should be valid data. Process and continue with the que
				[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(timeout) object:nil];
				[self process_response:buffer];
				[self setLastRequest:nil];			 //clear the last request
				[self processOneCommandFromQueue];	 //do the next command in the queue
			}
			//flush the accumulation buffer
			[buffer release];
			buffer = nil;
		}
	}
}


- (void) shipPressureValues
{
	if(shipPressures) {
		if([[ORGlobal sharedGlobal] runInProgress]){
			
			unsigned long data[kTPG256ARecordLength];
			data[0] = dataId | kTPG256ARecordLength;
			data[1] = [self uniqueIdNumber]&0xfff;
			
			union {
				float asFloat;
				unsigned long asLong;
			}theData;
			int index = 2;
			int i;
			for(i=0;i<6;i++){
				theData.asFloat = pressure[i];
				data[index] = theData.asLong;
				index++;
				
				data[index] = timeMeasured[i];
				index++;
			}
			[[NSNotificationCenter defaultCenter] postNotificationName:ORQueueRecordForShippingNotification 
																object:[NSData dataWithBytes:data length:sizeof(long)*kTPG256ARecordLength]];
		}
	}
}


#pragma mark •••Accessors

- (int) units
{
    return units;
}

- (void) setUnits:(int)aUnits
{
	if(aUnits>=0 && aUnits<=2){
		[[[self undoManager] prepareWithInvocationTarget:self] setUnits:units];
		units = aUnits;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelUnitsChanged object:self];
	}
}

- (int) measurementState:(int)index
{
	if(index>=0 && index<6)return measurementState[index];
	else return kTPG256AMeasurementNoSensor;
}

- (void) setMeasurementState:(int)index value:(int)aMeasurementState
{
	if(index>=0 && index<6) measurementState[index] = aMeasurementState;
}

- (float) pressureScaleValue
{
	return pressureScaleValue;
}

- (int) pressureScale
{
    return pressureScale;
}

- (void) setPressureScale:(int)aPressureScale
{
	if(aPressureScale<0)aPressureScale=0;
	else if(aPressureScale>11)aPressureScale=11;
	
    [[[self undoManager] prepareWithInvocationTarget:self] setPressureScale:pressureScale];
    
    pressureScale = aPressureScale;
	
	pressureScaleValue = powf(10.,(float)pressureScale);

    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelPressureScaleChanged object:self];
}

- (ORTimeRate*)timeRate:(int)index
{
	return timeRates[index];
}

- (BOOL) shipPressures
{
    return shipPressures;
}

- (void) setShipPressures:(BOOL)aShipPressures
{
    [[[self undoManager] prepareWithInvocationTarget:self] setShipPressures:shipPressures];
    
    shipPressures = aShipPressures;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelShipPressuresChanged object:self];
}

- (int) pollTime
{
    return pollTime;
}

- (void) setPollTime:(int)aPollTime
{
    [[[self undoManager] prepareWithInvocationTarget:self] setPollTime:pollTime];
    pollTime = aPollTime;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelPollTimeChanged object:self];

	if(pollTime){
		[self performSelector:@selector(pollPressures) withObject:nil afterDelay:2];
	}
	else {
		[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollPressures) object:nil];
	}
}


- (float) pressure:(int)index
{
	if(index>=0 && index<6)return pressure[index];
	else return 0.0;
}

- (unsigned long) timeMeasured:(int)index
{
	if(index>=0 && index<6)return timeMeasured[index];
	else return 0;
}

- (void) setPressure:(int)index value:(float)aValue;
{
	if(index>=0 && index<6){
		pressure[index] = aValue;
		//get the time(UT!)
		time_t	ut_Time;
		time(&ut_Time);
		timeMeasured[index] = ut_Time;

		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256APressureChanged 
															object:self 
														userInfo:[NSDictionary dictionaryWithObject:[NSNumber numberWithInt:index] forKey:@"Index"]];

		if(timeRates[index] == nil) timeRates[index] = [[ORTimeRate alloc] init];
		[timeRates[index] addDataToTimeAverage:aValue];

	}
}

- (NSString*) lastRequest
{
	return lastRequest;
}

- (void) setLastRequest:(NSString*)aRequest
{
	[lastRequest autorelease];
	lastRequest = [aRequest copy];    
}

- (BOOL) portWasOpen
{
    return portWasOpen;
}

- (void) setPortWasOpen:(BOOL)aPortWasOpen
{
    portWasOpen = aPortWasOpen;
}

- (NSString*) portName
{
    return portName;
}

- (void) setPortName:(NSString*)aPortName
{
    [[[self undoManager] prepareWithInvocationTarget:self] setPortName:portName];
    
    if(![aPortName isEqualToString:portName]){
        [portName autorelease];
        portName = [aPortName copy];    

        BOOL valid = NO;
        NSEnumerator *enumerator = [ORSerialPortList portEnumerator];
        ORSerialPort *aPort;
        while (aPort = [enumerator nextObject]) {
            if([portName isEqualToString:[aPort name]]){
                [self setSerialPort:aPort];
                if(portWasOpen){
                    [self openPort:YES];
                 }
                valid = YES;
                break;
            }
        } 
        if(!valid){
            [self setSerialPort:nil];
        }       
    }

    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelPortNameChanged object:self];
}

- (ORSerialPort*) serialPort
{
    return serialPort;
}

- (void) setSerialPort:(ORSerialPort*)aSerialPort
{
    [aSerialPort retain];
    [serialPort release];
    serialPort = aSerialPort;

    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelSerialPortChanged object:self];
}

- (void) openPort:(BOOL)state
{
    if(state) {
        [serialPort open];
		[serialPort setSpeed:9600];
		[serialPort setParityNone];
		[serialPort setStopBits2:0];
		[serialPort setDataBits:8];
		[serialPort commitChanges];
    }
    else      [serialPort close];
    portWasOpen = [serialPort isOpen];
	if([serialPort isOpen])[self sendUnits];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelPortStateChanged object:self];
}

- (double) lowLimit:(int)aChan
{
	if(aChan>=0 && aChan<6)return lowLimit[aChan];
	else return 1;
}

- (void) setLowLimit:(int)aChan value:(double)aValue
{
	if(aChan>=0 && aChan<6){
		[[[self undoManager] prepareWithInvocationTarget:self] setLowLimit:aChan value:lowLimit[aChan]];
		lowLimit[aChan] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelLowLimitChanged object:self];
	}
}
- (double) highLimit:(int)aChan
{
	if(aChan>=0 && aChan<6)return highLimit[aChan];
	else return 1;
}

- (void) setHighLimit:(int)aChan value:(double)aValue
{
	if(aChan>=0 && aChan<6){
		[[[self undoManager] prepareWithInvocationTarget:self] setHighLimit:aChan value:highLimit[aChan]];
		highLimit[aChan] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelHighLimitChanged object:self];
	}
}
- (double) lowAlarm:(int)aChan
{
	if(aChan>=0 && aChan<6)return lowAlarm[aChan];
	else return 1;
}

- (void) setLowAlarm:(int)aChan value:(double)aValue
{
	if(aChan>=0 && aChan<6){
		[[[self undoManager] prepareWithInvocationTarget:self] setHighAlarm:aChan value:lowAlarm[aChan]];
		lowAlarm[aChan] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelLowAlarmChanged object:self];
	}
}

- (double) highAlarm:(int)aChan
{
	if(aChan>=0 && aChan<6)return highAlarm[aChan];
	else return 1;
}

- (void) setHighAlarm:(int)aChan value:(double)aValue
{
	if(aChan>=0 && aChan<6){
		[[[self undoManager] prepareWithInvocationTarget:self] setHighAlarm:aChan value:highAlarm[aChan]];
		highAlarm[aChan] = aValue;
		[[NSNotificationCenter defaultCenter] postNotificationName:ORTPG256AModelHighAlarmChanged object:self];
	}
}

#pragma mark •••Archival
- (id) initWithCoder:(NSCoder*)decoder
{
	self = [super initWithCoder:decoder];
	[[self undoManager] disableUndoRegistration];
	[self setUnits:			[decoder decodeIntForKey:	 @"units"]];
	[self setPortWasOpen:	[decoder decodeBoolForKey:	 @"portWasOpen"]];
    [self setPortName:		[decoder decodeObjectForKey: @"portName"]];
	[self setPressureScale:	[decoder decodeIntForKey:	 @"pressureScale"]];
	[self setShipPressures:	[decoder decodeBoolForKey:	 @"shipPressures"]];
	[self setPollTime:		[decoder decodeIntForKey:	 @"pollTime"]];
	[[self undoManager] enableUndoRegistration];
	
	int i;
	for(i=0;i<6;i++){
		timeRates[i] = [[ORTimeRate alloc] init];
		[self setHighAlarm:i value:[decoder decodeDoubleForKey: [NSString stringWithFormat:@"highAlarm%d",i]]];
		[self setHighLimit:i value:[decoder decodeDoubleForKey: [NSString stringWithFormat:@"highLimit%d",i]]];
	}
    [self registerNotificationObservers];

	return self;
}

- (void) encodeWithCoder:(NSCoder*)encoder
{
    [super encodeWithCoder:encoder];
    [encoder encodeInt:units			forKey: @"units"];
    [encoder encodeInt:pressureScale	forKey: @"pressureScale"];
    [encoder encodeBool:shipPressures	forKey: @"shipPressures"];
    [encoder encodeInt:pollTime			forKey: @"pollTime"];
    [encoder encodeBool:portWasOpen		forKey: @"portWasOpen"];
    [encoder encodeObject:portName		forKey: @"portName"];
	
	int i;
	for(i=0;i<6;i++){
		[encoder encodeDouble:highAlarm[i] forKey: [NSString stringWithFormat:@"highAlarm%d",i]];
		[encoder encodeDouble:highLimit[i] forKey: [NSString stringWithFormat:@"highLimit%d",i]];
	}
}

#pragma mark ••• Commands
- (void) addCmdToQueue:(NSString*)aCmd
{
    if([serialPort isOpen]){ 
		if(!cmdQueue)cmdQueue = [[ORSafeQueue alloc] init];
		[cmdQueue enqueue:aCmd];
		if(!lastRequest){
			[self processOneCommandFromQueue];
		}
	}
}

- (void) readPressures
{
	@synchronized(self) {
		int i;
		for(i=0;i<6;i++){
			[self addCmdToQueue:[NSString stringWithFormat:@"PR%d",i+1]];
		}
		[self addCmdToQueue:@"++ShipRecords"];
	}
}

- (void) sendUnits
{
	[self addCmdToQueue:[NSString stringWithFormat:@"UNI,%d",units]];
}

#pragma mark •••Data Records
- (unsigned long) dataId { return dataId; }
- (void) setDataId: (unsigned long) DataId
{
    dataId = DataId;
}
- (void) setDataIds:(id)assigner
{
    dataId       = [assigner assignDataIds:kLongForm];
}

- (void) syncDataIdsWith:(id)anotherTPG256A
{
    [self setDataId:[anotherTPG256A dataId]];
}

- (void) appendDataDescription:(ORDataPacket*)aDataPacket userInfo:(id)userInfo
{
    //----------------------------------------------------------------------------------------
    // first add our description to the data description
    [aDataPacket addDataDescriptionItem:[self dataRecordDescription] forKey:@"TPG256AModel"];
}

- (NSDictionary*) dataRecordDescription
{
    NSMutableDictionary* dataDictionary = [NSMutableDictionary dictionary];
    NSDictionary* aDictionary = [NSDictionary dictionaryWithObjectsAndKeys:
        @"ORTPG256ADecoderForPressure",					@"decoder",
        [NSNumber numberWithLong:dataId],				@"dataId",
        [NSNumber numberWithBool:NO],					@"variable",
        [NSNumber numberWithLong:kTPG256ARecordLength], @"length",
        nil];
    [dataDictionary setObject:aDictionary forKey:@"Pressures"];
    
    return dataDictionary;
}
#pragma mark •••Adc Processing Protocol
- (void) processIsStarting
{
	[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollPressures) object:nil];
    readOnce = NO;
}

- (void) processIsStopping
{
	[self pollPressures];
}

//note that everything called by these routines MUST be threadsafe
- (void) startProcessCycle
{    
	if(!readOnce){
		@try { 
			if([cmdQueue count] == 0) {
				[self readPressures]; 
				readOnce = YES;
			}
		}
		@catch(NSException* localException) { 
			//catch this here to prevent it from falling thru, but nothing to do.
		}
	}	
}

- (void) endProcessCycle
{
    readOnce = NO;
}

- (NSString*) identifier
{
	NSString* s;
 	@synchronized(self){
		s= [NSString stringWithFormat:@"TPG256A,%d",[self uniqueIdNumber]];
	}
	return s;
}

- (NSString*) processingTitle
{
	NSString* s;
 	@synchronized(self){
		s= [self identifier];
	}
	return s;
}

- (double) convertedValue:(int)aChan
{
	double theValue = 0;
	@synchronized(self){
		if(aChan>=0 && aChan<6)return pressure[aChan];
 	}
	return theValue;
}

- (double) maxValueForChan:(int)aChan
{
	double theValue;
	@synchronized(self){
        if(aChan>=0 && aChan<6) theValue = highLimit[aChan];
		else         theValue = 1.0;
	}
	return theValue;
}

- (double) minValueForChan:(int)aChan
{
	double theValue;
	@synchronized(self){
        if(aChan>=0 && aChan<6) theValue = lowLimit[aChan];
		else         theValue = 1.0;
	}
	return theValue;
}

- (void) getAlarmRangeLow:(double*)theLowAlarm high:(double*)theHighAlarm channel:(int)aChan
{
	@synchronized(self){
        if(aChan>=0 && aChan<6) {
            *theLowAlarm   = lowAlarm[aChan];
            *theHighAlarm = highAlarm[aChan];
        }
        else {
			*theLowAlarm = 0;
            *theHighAlarm = 1E-4;
        }
	}		
}

- (BOOL) processValue:(int)aChan
{
	BOOL r = 0;
	@synchronized(self){
		if(aChan>=0 && aChan<6)r =  pressure[aChan];
    }
	return r;
}

- (void) setProcessOutput:(int)channel value:(int)value
{
    //nothing to do. not used in adcs. really shouldn't be in the protocol
}

@end

@implementation ORTPG256AModel (private)
- (void) runStarted:(NSNotification*)aNote
{
}

- (void) runStopped:(NSNotification*)aNote
{
}

- (void) timeout
{
	NSLogError(@"TGP262",@"command timeout",nil);
	[self setLastRequest:nil];
	[self processOneCommandFromQueue];	 //do the next command in the queue
}

- (void) processOneCommandFromQueue
{
	if([cmdQueue count] == 0) return;
	NSString* aCmd = [cmdQueue dequeue];
	if([aCmd isEqualToString:@"++ShipRecords"]){
		[self shipPressureValues];
	}
	else {
		if(![aCmd hasSuffix:@"\r\n"]) {
			aCmd = [aCmd stringByReplacingOccurrencesOfString:@"\n" withString:@""];
			aCmd = [aCmd stringByReplacingOccurrencesOfString:@"\r" withString:@""];
			aCmd = [aCmd stringByAppendingString:@"\r\n"];
		}
		[self setLastRequest:aCmd];
		[self performSelector:@selector(timeout) withObject:nil afterDelay:3];
		//just sent a command so the first thing received should be an ACK
		//enter that state and send the command
		portDataState = kWaitingForACK;
		[serialPort writeString:aCmd];
	}
}

- (void) process_response:(NSString*)theResponse
{
	theResponse = [theResponse stringByReplacingOccurrencesOfString:@"\n" withString:@""];
	theResponse = [theResponse stringByReplacingOccurrencesOfString:@"\r" withString:@""];
	if([lastRequest hasPrefix:@"PR"]){
		int channel = [[lastRequest substringWithRange:NSMakeRange(2,1)] intValue]-1;
		if(channel>=0 && channel<6){
			NSArray* parts = [theResponse componentsSeparatedByString:@","];
			int n = [parts count];
			if(n == 2){
				[self setMeasurementState:channel value:[[parts objectAtIndex:0] intValue]];
				float thePressure = 0;
				if(measurementState[channel] == kTPG256AMeasurementOK){
					thePressure = [[parts objectAtIndex:1] floatValue];
				}
				[self setPressure:channel value:thePressure];
			}
		}
	}
	else if([lastRequest hasPrefix:@"UNI"]){
		//for now just ignore and let the select by the user stand....
	}
}

- (void) pollPressures
{
	[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(pollPressures) object:nil];
	if(pollTime){
		[self readPressures];
		[self performSelector:@selector(pollPressures) withObject:nil afterDelay:pollTime];
	}
}


@end
