//--------------------------------------------------------
// ORcPCIcpuController
// Created by Mark  A. Howe on Tue Feb 07 2006
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2006 CENPA, University of Washington. All rights reserved.
//--------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#import "OrcaObjectController.h"

@class ORQueueView;
@class ORTimedTextField;
@class ORValueBar;

@interface SBC_LinkController : OrcaObjectController
{
	IBOutlet NSButton*				lockButton;
	IBOutlet NSTabView*				tabView;
    IBOutlet ORGroupView*			groupView;

	//code management
	IBOutlet NSButton*		setFilePathButton;
	IBOutlet NSButton*      toggleCrateButton;
	IBOutlet NSButton*      verboseButton;
	IBOutlet NSButton*      forceReloadButton;
	IBOutlet ORTimedTextField*  statusField;
	IBOutlet NSTextField*   connectionStatusField;
	IBOutlet NSButton*      killCrateButton;
	IBOutlet NSMatrix*		loadModeMatrix;
	IBOutlet NSTextField*   filePathField;

	//Monitoring
	IBOutlet NSTextField*   runInfoField;
	IBOutlet ORQueueView*   queView;
	IBOutlet ORValueBar*    bytesSentRateBar;
	IBOutlet ORValueBar*    bytesReceivedRateBar;	
	IBOutlet NSTextField*   byteRateSentField;
	IBOutlet NSTextField*   byteRateReceivedField;
	IBOutlet NSMatrix*      infoTypeMatrix;

	//IP Settings
	IBOutlet NSTextField*	ipNumberField;
	IBOutlet NSTextField*	portNumberField;
	IBOutlet NSSecureTextField* passWordField;
	IBOutlet NSTextField*   userNameField;
	IBOutlet NSTextField*	connectionStatus1Field;
	IBOutlet NSButton*		initAfterConnectButton;
	IBOutlet NSButton*		connectButton;
	IBOutlet NSButton*		connect1Button;
	IBOutlet NSTextField*	status1Field;

	//Basic Ops
	IBOutlet NSTextField*	functionAllowedField;
	IBOutlet NSTextField*	addressField;
	IBOutlet NSStepper*		addressStepper;
	IBOutlet NSTextField*	writeValueField;
	IBOutlet NSStepper*		writeValueStepper;
	IBOutlet NSButton*		readButton;
	IBOutlet NSButton*		writeButton;
	IBOutlet NSButton*		resetCrateBusButton;
	IBOutlet NSTextField*	rangeTextField;
	IBOutlet NSStepper* 	rangeStepper;
	IBOutlet NSButton*		doRangeButton;
	IBOutlet NSMatrix*      readWriteTypeMatrix;
	IBOutlet NSPopUpButton* addressModifierPU;
}

#pragma mark •••Initialization

- (void) dealloc;
- (void) awakeFromNib;

#pragma mark •••Notifications

- (void) registerNotificationObservers;
- (void) updateWindow;

#pragma mark ***Interface Management
- (void) settingsLockChanged:(NSNotification*)aNote;

- (void) filePathChanged:(NSNotification*)aNote;
- (void) verboseChanged:(NSNotification*)aNote;
- (void) forceReloadChanged:(NSNotification*)aNote;
- (void) startStatusChanged:(NSNotification*)aNote;
- (void) setToggleCrateButtonState;
- (void) loadModeChanged:(NSNotification*)aNote;

- (void) byteRateChanged:(NSNotification*)aNote;
- (void) runInfoChanged:(NSNotification*)aNote;
- (void) infoTypeChanged:(NSNotification*)aNote;

- (void) initAfterConnectChanged:(NSNotification*)aNote;
- (void) startStatusChanged:(NSNotification*)aNote;
- (void) sbcLockChanged:(NSNotification*)aNote;
- (void) userNameChanged:(NSNotification*)aNote;
- (void) passWordChanged:(NSNotification*)aNote;
- (void) ipNumberChanged:(NSNotification*)aNote;
- (void) portNumberChanged:(NSNotification*)aNote;
- (void) lamSlotChanged:(NSNotification*)aNotification;

- (void) addressChanged:(NSNotification*)aNote;
- (void) writeValueChanged:(NSNotification*)aNote;
- (void) rangeChanged:(NSNotification*)aNote;
- (void) doRangeChanged:(NSNotification*)aNote;
- (void) readWriteTypeChanged:(NSNotification*)aNote;
- (void) addressModifierChanged:(NSNotification*)aNote;

- (NSString*) errorString:(int)errNum;
- (NSString*) literalToString:(int)aLiteral;


#pragma mark •••Actions
- (IBAction) lockAction:(id)sender;

- (IBAction) loadModeAction:(id)sender;
- (IBAction) filePathAction:(id)sender;
- (IBAction) verboseAction:(id)sender;
- (IBAction) forceReloadAction:(id)sender;
- (IBAction) toggleCrateAction:(id)sender;
- (IBAction) killCrateAction:(id)sender;

- (IBAction) initAfterConnectAction:(id)sender;
- (IBAction) ipNumberAction:(id)sender;
- (IBAction) portNumberAction:(id)sender;
- (IBAction) userNameAction:(id)sender;
- (IBAction) passWordAction:(id)sender;
- (IBAction) connectionAction:(id)sender;

- (IBAction) addressAction:(id)sender;
- (IBAction) writeValueAction:(id)sender;
- (IBAction) writeAction:(id)sender;
- (IBAction) readAction:(id)sender;
- (IBAction) resetCrateBusAction:(id)sender;

- (IBAction) rangeTextFieldAction:(id)sender;
- (IBAction) doRangeAction:(id)sender;
- (IBAction) readWriteTypeMatrixAction:(id)sender;
- (IBAction) addressModifierPUAction:(id)sender;

- (IBAction) infoTypeAction:(id)sender;

#pragma mark •••DataSource
- (void) getQueMinValue:(unsigned long*)aMinValue maxValue:(unsigned long*)aMaxValue head:(unsigned long*)aHeadValue tail:(unsigned long*)aTailValue;
@end
@interface OrcaObject (SBC_Link)
- (BOOL) showBasicOps;
@end
