//--------------------------------------------------------
// ORPacModel
// Created by Mark  A. Howe on Tue Jan 6, 2009
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2005 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark •••Imported Files

@class ORSerialPort;
@class ORTimeRate;

#define kPacShipAdcs	0xff

//Main Cmd Bytes
#define kPacADCmd		0x01    //--II.
#define kPacSelCmd		0x02	//--III.
#define kPacLcmEnaCmd	0x04	//-->IV.
#define kPacRDacCmd		0x10	//-->V.
//followed by zero or more bytes

//Secondary Cmd Bytes
//II.
#define kPacSelectMask 0x07

//III.
//no further command byte

//IV.
#define kPacLcmEnaSet   0x01		
#define kPacLcmEnaClr   0x02	

//V.
#define kPacRDacWriteAll		0x01 //write all with same value. 2 data words follow		
#define kPacRDacReadAll			0x02 //Read all	
#define kPacRDacWriteOneRDac    0x10 //Write One RDAC.  Position follows (1 Byte) Value Follows (two bytes)	
#define kPacRDacReadOneRDac		0x20 //Read One RDAC.   Position follows (1 Byte) Output of two bytes	

#define kPacOkByte				0xf0
#define kPacErrorByte			0x0f

@interface ORPacModel : OrcaObject
{
    @private
        NSString*			portName;
        BOOL				portWasOpen;
        ORSerialPort*		serialPort;
        unsigned long		dataId;
		NSData*				lastRequest;
		NSMutableArray*		cmdQueue;
		unsigned short		adc[8];
		unsigned long		timeMeasured[8];
		int					pollTime;
        NSMutableString*    buffer;
		BOOL				shipAdcs;
		ORTimeRate*			timeRates[8];
		NSMutableData*		inComingData;
		unsigned char		portDMask;
		unsigned short		dac[8];
}

#pragma mark •••Initialization

- (id)   init;
- (void) dealloc;

- (void) registerNotificationObservers;
- (void) dataReceived:(NSNotification*)note;

#pragma mark •••Accessors
- (ORTimeRate*)timeRate:(int)index;
- (BOOL) shipAdcs;
- (void) setShipAdcs:(BOOL)aShipAdcs;
- (int)  pollTime;
- (void) setPollTime:(int)aPollTime;
- (ORSerialPort*) serialPort;
- (void) setSerialPort:(ORSerialPort*)aSerialPort;
- (BOOL) portWasOpen;
- (void) setPortWasOpen:(BOOL)aPortWasOpen;
- (NSString*) portName;
- (void) setPortName:(NSString*)aPortName;
- (NSData*) lastRequest;
- (void) setLastRequest:(NSData*)aRequest;
- (void) openPort:(BOOL)state;
- (unsigned short) adc:(int)index;
- (unsigned long) timeMeasured:(int)index;
- (void) setAdc:(int)index value:(unsigned short)aValue;
- (void) setPortDMask:(unsigned char)aMask;
- (BOOL) portDBit:(int)i;
- (unsigned short) dac:(int)index;
- (void) setDac:(int)index value:(unsigned short)aValue;

#pragma mark •••Data Records
- (void) appendDataDescription:(ORDataPacket*)aDataPacket userInfo:(id)userInfo;
- (NSDictionary*) dataRecordDescription;
- (unsigned long) dataId;
- (void) setDataId: (unsigned long) DataId;
- (void) setDataIds:(id)assigner;
- (void) syncDataIdsWith:(id)anotherPac;
- (void) writePortD;
- (void) writeDacs;
- (void) readDacs;
- (void) shipAdcValues;

#pragma mark •••Commands
- (void) enqueReadADC:(int)aChannel;
- (void) enqueWritePortD;
- (void) enqueWriteDac:(int)aChannel;
- (void) enqueReadDac:(int)aChannel;

- (void) enqueShipCmd;
- (void) readAdcs;

- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;

@end


extern NSString* ORPacModelShipAdcsChanged;
extern NSString* ORPacModelPollTimeChanged;
extern NSString* ORPacModelSerialPortChanged;
extern NSString* ORPacLock;
extern NSString* ORPacModelPortNameChanged;
extern NSString* ORPacModelPortStateChanged;
extern NSString* ORPacModelAdcChanged;
extern NSString* ORPacModelPortDMaskChanged;
extern NSString* ORPacModelDacChanged;
