//--------------------------------------------------------
// ORRGA300Model
// Created by Mark  A. Howe on Wed 4/15/2009
// Created by Mark  A. Howe on Tues Jan 4, 2012
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2012 CENPA, University of Washington. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//Washington at the Center for Experimental Nuclear Physics and 
//Astrophysics (CENPA) sponsored in part by the United States 
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//Washington reserve all rights in the program. Neither the authors,
//University of Washington, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark •••Imported Files
#import "ORSerialPortModel.h"

@class ORSafeQueue;
@class ORTimeRate;
@class ORAlarm;

//Status Error Masks
#define kRGACommStatusMask			0x01
#define kRGAFilamentStatusMask		0x02
#define kRGAElectronMultiStatusMask	0x08
#define kRGAQMFStatusMask			0x10
#define kRGAElectrometerStatusMask	0x20
#define kRGA24VStatusMask			0x40

//RS2323 Error Masks
#define kRGABadCmd			0x01
#define kRGABadParam		0x02
#define kRGACmdTooLong		0x04
#define kRGAOverWrite		0x08
#define kRGATransOverWrite	0x10
#define kRGAJumper			0x20
#define kRGAParamConflict	0x40

//CEM Masks
#define kRGACEMNoElecMultiOption	0x10

//FIL Masks
#define kRGAFILSingleFilament		0x01
#define kRGAFILPressureTooHigh		0x20
#define kRGAFILCannotSetCurrent	0x40
#define kRGAFILNoFilament			0x80

//QMG Masks
#define kRGAQMFCurrentLimited	0x10
#define kRGAQMFCurrentTooHigh	0x40
#define kRGAQMFRF_CTTooHigh		0x80

//Power Supply Masks
#define kRGAPSExtPowerTooLow  0x40
#define kRGAPSExtPowerTooHigh 0x80

//Electrometer Masks
#define kRGADetOpAmpOffset	0x02
#define kRGADetCompNegInput 0x08
#define kRGADetCompPosInput 0x10
#define kRGADetDetNegInput  0x20
#define kRGADetDetPosInput  0x40
#define kRGADetAdcFailure	0x80


@interface ORRGA300Model : ORSerialPortModel
{
    @private
        unsigned long	dataId;
		NSString*		lastRequest;
		ORSafeQueue*	cmdQueue;
		NSMutableData*	inComingData;
		int				pollTime;
		ORTimeRate*		timeRate;
		int		modelNumber;
		float	firmwareVersion;
		int		serialNumber;
		int		statusWord;
		int		psErrWord;
		int		detErrWord;
		int		qmfErrWord;
		int		cemErrWord;
		int		filErrWord;
		int		rs232ErrWord;
	
		//ionizer
		int		ionizerDegassTime;
		int		ionizerElectronEnergy;
		int		ionizerEmissionCurrent;
		int		ionizerIonEnergy;
		int		ionizerFocusPlateVoltage;
		int		elecMultHVBias;
		int		noiseFloorSetting;
		int		analogScanPoints;
		int		histoScanPoints;
		int		finalMass;
		int		initialMass;
		int		singleMass;
		int		stepsPerAmu;
		int		numberAnalogScans;
    int measuredIonCurrent;
    BOOL electronMultiOption;
}

#pragma mark •••Initialization
- (void) dealloc;

#pragma mark •••Accessors
- (BOOL) electronMultiOption;
- (int) measuredIonCurrent;
- (void) setMeasuredIonCurrent:(int)aMeasuredIonCurrent;
//scanning
- (int)		numberAnalogScans;
- (void)	setNumberAnalogScans:(int)aNumberAnalogScans;
- (int)		stepsPerAmu;
- (void)	setStepsPerAmu:(int)aStepsPerAmu;
- (int)		singleMass;
- (void)	setSingleMass:(int)aSingleMass;
- (int)		histoScanPoints;
- (int)		analogScanPoints;
- (int)		noiseFloorSetting;
- (void)	setNoiseFloorSetting:(int)aNoiseFloorSetting;
- (int)		initialMass;
- (void)	setInitialMass:(int)aInitialMass;
- (int)		finalMass;
- (void)	setFinalMass:(int)aFinalMass;

- (int)		elecMultHVBias;
- (void)	setElecMultHVBias:(int)aElecMultHVBias;

//ionizer
- (int)		ionizerFocusPlateVoltage;
- (void)	setIonizerFocusPlateVoltage:(int)aIonizerFocusPlateVoltage;
- (int)		ionizerIonEnergy;
- (void)	setIonizerIonEnergy:(int)aIonizerIonEnergy;
- (int)		ionizerEmissionCurrent;
- (void)	setIonizerEmissionCurrent:(int)aIonizerEmissionCurrent;
- (int)		ionizerElectronEnergy;
- (void)	setIonizerElectronEnergy:(int)aIonizerElectronEnergy;
- (int)		ionizerDegassTime;
- (void)	setIonizerDegassTime:(int)aIonizerDegassTime;

//status stuff
- (int) rs232ErrWord;
- (void) setRs232ErrWord:(int)aRs232ErrWord;
- (int) filErrWord;
- (void) setFilErrWord:(int)aFilErrWord;
- (int) cemErrWord;
- (void) setCemErrWord:(int)aCemErrWord;
- (int) qmfErrWord;
- (void) setQmfErrWord:(int)aQmfErrWord;
- (int) detErrWord;
- (void) setDetErrWord:(int)aDetErrWord;
- (int) psErrWord;
- (void) setPsErrWord:(int)aPsErrWord;

- (int)		statusWord;
- (void)	setStatusWord:(int)aStatusWord;
- (int)		serialNumber;
- (float)	firmwareVersion;
- (int)		modelNumber;

- (int)  pollTime;
- (void) setPollTime:(int)aPollTime;
- (ORTimeRate*)timeRate;
- (NSString*) lastRequest;
- (void) setLastRequest:(NSString*)aCmdString;
- (void) openPort:(BOOL)state;

#pragma mark •••Commands
- (void) syncWithHW;
- (void) sendIDRequest;
- (void) sendInitComm;
- (void) sendReset;	
- (void) sendStandBy;	
- (void) sendErrQuery;
- (void) sendRS232ErrQuery;
- (void) sendDetErrQuery; 
- (void) sendFilamentErrQuery; 
- (void) sendEMErrQuery; 
- (void) sendPowerErrQuery; 
- (void) sendQMFErrQuery; 

- (void) sendIonizerElectronEnergy;
- (void) sendIonizerEmissionCurrent; 
- (void) sendIonizerIonEnergy;
- (void) sendIonizerFocusPlateVoltage;

- (void) sendCalibrateAll;
- (void) sendCalibrateElectrometerIVResponse;
- (void) sendElecMultiHVBias;

- (void) startDegassing;
- (void) stopDegassing;

- (void) sendInitialMass;
- (void) sendFinalMass;


- (void) startSingleMassMeasurement;
- (void) stopSingleMassMeasurement;
- (void) sendStepsPerAmuQuery;
- (void) startAnalogScan;
- (void) stopAnalogScan;

#pragma mark •••Data Records
- (void) appendDataDescription:(ORDataPacket*)aDataPacket userInfo:(id)userInfo;
- (NSDictionary*) dataRecordDescription;
- (unsigned long) dataId;
- (void) setDataId: (unsigned long) DataId;
- (void) setDataIds:(id)assigner;
- (void) syncDataIdsWith:(id)anotherRGA300;

#pragma mark •••Archival
- (id)   initWithCoder:(NSCoder*)decoder;
- (void) encodeWithCoder:(NSCoder*)encoder;

#pragma mark •••Command Methods
- (void) sendIDRequest;

#pragma mark •••Port Methods
- (void) dataReceived:(NSNotification*)note;

#pragma mark •••HW Methods
- (void) initUnit;
- (void) updateAll;

@end

extern NSString* ORRGA300ModelElectronMultiOptionChanged;
extern NSString* ORRGA300ModelMeasuredIonCurrentChanged;
extern NSString* ORRGA300ModelNumberAnalogScansChanged;
extern NSString* ORRGA300ModelStepsPerAmuChanged;
extern NSString* ORRGA300ModelSingleMassChanged;
extern NSString* ORRGA300ModelInitialMassChanged;
extern NSString* ORRGA300ModelFinalMassChanged;
extern NSString* ORRGA300ModelHistoScanPointsChanged;
extern NSString* ORRGA300ModelAnalogScanPointsChanged;
extern NSString* ORRGA300ModelNoiseFloorSettingChanged;
extern NSString* ORRGA300ModelElecMultHVBiasChanged;
extern NSString* ORRGA300ModelIonizerFocusPlateVoltageChanged;
extern NSString* ORRGA300ModelIonizerIonEnergyChanged;
extern NSString* ORRGA300ModelIonizerEmissionCurrentChanged;
extern NSString* ORRGA300ModelIonizerElectronEnergyChanged;
extern NSString* ORRGA300ModelIonizerDegassTimeChanged;
extern NSString* ORRGA300ModelRs232ErrWordChanged;
extern NSString* ORRGA300ModelFilErrWordChanged;
extern NSString* ORRGA300ModelCemErrWordChanged;
extern NSString* ORRGA300ModelQmfErrWordChanged;
extern NSString* ORRGA300ModelDetErrWordChanged;
extern NSString* ORRGA300ModelPsErrWordChanged;
extern NSString* ORRGA300ModelStatusWordChanged;
extern NSString* ORRGA300ModelSerialNumberChanged;
extern NSString* ORRGA300ModelFirmwareVersionChanged;
extern NSString* ORRGA300ModelModelNumberChanged;

extern NSString* ORRGA300Lock;
extern NSString* ORRGA300ModelPollTimeChanged;
