//--------------------------------------------------------
// ORHVcRIOModel
// Created by Mark  A. Howe on Oct 17, 2017
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2017, University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of 
//North Carolina sponsored in part by the United States
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020. 
//The University has certain rights in the program pursuant to 
//the contract and the program should not be copied or distributed 
//outside your organization.  The DOE and the University of 
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty, 
//express or implied, or assume any liability or responsibility 
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files
#import "ORHVcRIOModel.h"
#import "ORSafeQueue.h"
#import "NetSocket.h"

#pragma mark ***External Strings
NSString* ORHVcRIOModelIsConnectedChanged       = @"ORHVcRIOModelIsConnectedChanged";
NSString* ORHVcRIOModelIpAddressChanged         = @"ORHVcRIOModelIpAddressChanged";
NSString* ORHVcRIOModelSetPointChanged          = @"ORHVcRIOModelSetPointChanged";
NSString* ORHVcRIOModelReadBackChanged          = @"ORHVcRIOModelReadBackChanged";
NSString* ORHVcRIOModelQueCountChanged          = @"ORHVcRIOModelQueCountChanged";
NSString* ORHVcRIOModelSetPointsChanged         = @"ORHVcRIOModelSetPointsChanged";
NSString* ORHVcRIOModelMeasuredValuesChanged    = @"ORHVcRIOModelMeasuredValuesChanged";
NSString* ORHVcRIOModelSetPointFileChanged      = @"ORHVcRIOModelSetPointFileChanged";
NSString* ORHVcRIOLock						    = @"ORHVcRIOLock";

//new lists from 10/17/2017   -mah-

static NSString* setPointList[] = {
    @"Zeitstempel",    @"-",
    @"Zeitstempel",    @"-",
    @"SOLL_PXI_MODUL#WestModul0",    @"Rampe",
    @"SOLL_PXI_MODUL#WestModul1",    @"Rampe",
    @"SOLL_PXI_MODUL#WestModul2",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul0",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul1",    @"Rampe",
    @"SOLL_PXI_MODUL#EastModul2",    @"Rampe",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh0",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh1",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh2",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh3",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh4",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh5",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh6",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh7",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh8",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh9",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh10",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh11",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh12",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh13",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh14",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh15",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh16",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh17",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh18",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh19",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh20",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh21",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh22",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#WestCh23",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh0",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh1",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh2",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh3",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh4",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh5",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh6",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh7",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh8",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh9",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh10",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh11",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh12",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh13",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh14",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh15",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh16",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh17",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh18",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh19",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh20",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh21",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh22",    @"U_EXAKT",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"U_SOLL",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"I_MAX",
    @"SOLL_PXI_CHANNEL#EastCh23",    @"U_EXAKT",
    @"SOLL_EHV#mainSpecVesel",    @"U_Soll",
    @"SOLL_EHV#mainSpecVesel",    @"I_MAX",
    @"SOLL_EHV#mainSpecVesel",    @"Rampe",
    @"SOLL_EHV#mainSpecElektrode",    @"U_Soll",
    @"SOLL_EHV#mainSpecElektrode",    @"I_MAX",
    @"SOLL_EHV#mainSpecElektrode",    @"Rampe",
    @"SOLL_EHV#mainSpecCorrSouth",    @"U_Soll",
    @"SOLL_EHV#mainSpecCorrSouth",    @"I_MAX",
    @"SOLL_EHV#mainSpecCorrSouth",    @"Rampe",
    @"SOLL_EHV#mainSpecCorrWest",    @"U_Soll",
    @"SOLL_EHV#mainSpecCorrWest",    @"I_MAX",
    @"SOLL_EHV#mainSpecCorrWest",    @"Rampe",
    @"SOLL_EHV#mainSpecDipolWest",    @"U_Soll",
    @"SOLL_EHV#mainSpecDipolWest",    @"I_MAX",
    @"SOLL_EHV#mainSpecDipolWest",    @"Rampe",
    @"SOLL_EHV#mainSpecDipolEast",    @"U_Soll",
    @"SOLL_EHV#mainSpecDipolEast",    @"I_MAX",
    @"SOLL_EHV#mainSpecDipolEast",    @"Rampe",
    @"SOLL_EHV#IECommon",    @"U_Soll",
    @"SOLL_EHV#IECommon",    @"I_MAX",
    @"SOLL_EHV#IECommon",    @"Rampe",
    @"SOLL_EHV#preSpecVesel",    @"U_Soll",
    @"SOLL_EHV#preSpecVesel",    @"I_MAX",
    @"SOLL_EHV#preSpecVesel",    @"Rampe",
    @"SOLL_EHV#preSpecIE1",    @"U_Soll",
    @"SOLL_EHV#preSpecIE1",    @"I_MAX",
    @"SOLL_EHV#preSpecIE1",    @"Rampe",
    @"SOLL_EHV#preSpecIE2",    @"U_Soll",
    @"SOLL_EHV#preSpecIE2",    @"I_MAX",
    @"SOLL_EHV#preSpecIE2",    @"Rampe",
    @"SOLL_EHV#preSpecIE3",    @"U_Soll",
    @"SOLL_EHV#preSpecIE3",    @"I_MAX",
    @"SOLL_EHV#preSpecIE3",    @"Rampe",
    @"SOLL_EHV#preSpecIE4",    @"U_Soll",
    @"SOLL_EHV#preSpecIE4",    @"I_MAX",
    @"SOLL_EHV#preSpecIE4",    @"Rampe",
    @"SOLL_STATUS#Ost_Relais",    @"Bed",
    @"SOLL_STATUS#Ost_Relais",    @"Modus",
    @"SOLL_STATUS#Ost_Relais",    @"Time_On",
    @"SOLL_STATUS#Ost_Relais",    @"Time_Off",
    @"SOLL_STATUS#West_Relais",    @"Bed",
    @"SOLL_STATUS#West_Relais",    @"Modus",
    @"SOLL_STATUS#West_Relais",    @"Time_On",
    @"SOLL_STATUS#West_Relais",    @"Time_Off",
    @"SOLL_EHV#postReg",    @"U_Soll",
    @"SOLL_EHV#postRegInhibit",    @"Status",
    @"", @""
};



static NSString* measuredValueList[] = {
    @"Zeitstempel",    @"-",
    @"Zeitstempel",    @"-",
    @"IST_PXI_MODUL#WestModul0",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul0",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul0",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul0",    @"Rampe",
    @"IST_PXI_MODUL#WestModul0",    @"Warnung",
    @"IST_PXI_MODUL#WestModul0",    @"Fehler",
    @"IST_PXI_MODUL#WestModul1",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul1",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul1",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul1",    @"Rampe",
    @"IST_PXI_MODUL#WestModul1",    @"Warnung",
    @"IST_PXI_MODUL#WestModul1",    @"Fehler",
    @"IST_PXI_MODUL#WestModul2",    @"Temperatur Board",
    @"IST_PXI_MODUL#WestModul2",    @"24 Spannung",
    @"IST_PXI_MODUL#WestModul2",    @"5V Spannung",
    @"IST_PXI_MODUL#WestModul2",    @"Rampe",
    @"IST_PXI_MODUL#WestModul2",    @"Warnung",
    @"IST_PXI_MODUL#WestModul2",    @"Fehler",
    @"IST_PXI_MODUL#EastModul0",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul0",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul0",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul0",    @"Rampe",
    @"IST_PXI_MODUL#EastModul0",    @"Warnung",
    @"IST_PXI_MODUL#EastModul0",    @"Fehler",
    @"IST_PXI_MODUL#EastModul1",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul1",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul1",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul1",    @"Rampe",
    @"IST_PXI_MODUL#EastModul1",    @"Warnung",
    @"IST_PXI_MODUL#EastModul1",    @"Fehler",
    @"IST_PXI_MODUL#EastModul2",    @"Temperatur Board",
    @"IST_PXI_MODUL#EastModul2",    @"24 Spannung",
    @"IST_PXI_MODUL#EastModul2",    @"5V Spannung",
    @"IST_PXI_MODUL#EastModul2",    @"Rampe",
    @"IST_PXI_MODUL#EastModul2",    @"Warnung",
    @"IST_PXI_MODUL#EastModul2",    @"Fehler",
    @"IST_EHV#mainSpecVessel",    @"U_SOLL",
    @"IST_EHV#mainSpecVessel",    @"U_IST",
    @"IST_EHV#mainSpecVessel",    @"I_MAX",
    @"IST_EHV#mainSpecVessel",    @"I_IST",
    @"IST_EHV#mainSpecVessel",    @"Rampe",
    @"IST_EHV#mainSpecVessel",    @"I_Begrenzt",
    @"IST_EHV#mainSpecVessel",    @"Warnung",
    @"IST_EHV#mainSpecVessel",    @"Fehler",
    @"IST_EHV#mainSpecElektrode",    @"U_SOLL",
    @"IST_EHV#mainSpecElektrode",    @"U_IST",
    @"IST_EHV#mainSpecElektrode",    @"I_MAX",
    @"IST_EHV#mainSpecElektrode",    @"I_IST",
    @"IST_EHV#mainSpecElektrode",    @"Rampe",
    @"IST_EHV#mainSpecElektrode",    @"I_Begrenzt",
    @"IST_EHV#mainSpecElektrode",    @"Warnung",
    @"IST_EHV#mainSpecElektrode",    @"Fehler",
    @"IST_EHV#mainSpecCorrSouth",    @"U_SOLL",
    @"IST_EHV#mainSpecCorrSouth",    @"U_IST",
    @"IST_EHV#mainSpecCorrSouth",    @"I_MAX",
    @"IST_EHV#mainSpecCorrSouth",    @"I_IST",
    @"IST_EHV#mainSpecCorrSouth",    @"Rampe",
    @"IST_EHV#mainSpecCorrSouth",    @"I_Begrenzt",
    @"IST_EHV#mainSpecCorrSouth",    @"Warnung",
    @"IST_EHV#mainSpecCorrSouth",    @"Fehler",
    @"IST_EHV#mainSpecCorrNorth",    @"U_SOLL",
    @"IST_EHV#mainSpecCorrNorth",    @"U_IST",
    @"IST_EHV#mainSpecCorrNorth",    @"I_MAX",
    @"IST_EHV#mainSpecCorrNorth",    @"I_IST",
    @"IST_EHV#mainSpecCorrNorth",    @"Rampe",
    @"IST_EHV#mainSpecCorrNorth",    @"I_Begrenzt",
    @"IST_EHV#mainSpecCorrNorth",    @"Warnung",
    @"IST_EHV#mainSpecCorrNorth",    @"Fehler",
    @"IST_EHV#mainSpecDipolWest",    @"U_SOLL",
    @"IST_EHV#mainSpecDipolWest",    @"U_IST",
    @"IST_EHV#mainSpecDipolWest",    @"I_MAX",
    @"IST_EHV#mainSpecDipolWest",    @"I_IST",
    @"IST_EHV#mainSpecDipolWest",    @"Rampe",
    @"IST_EHV#mainSpecDipolWest",    @"I_Begrenzt",
    @"IST_EHV#mainSpecDipolWest",    @"Warnung",
    @"IST_EHV#mainSpecDipolWest",    @"Fehler",
    @"IST_EHV#mainSpecDipolEast",    @"U_SOLL",
    @"IST_EHV#mainSpecDipolEast",    @"U_IST",
    @"IST_EHV#mainSpecDipolEast",    @"I_MAX",
    @"IST_EHV#mainSpecDipolEast",    @"I_IST",
    @"IST_EHV#mainSpecDipolEast",    @"Rampe",
    @"IST_EHV#mainSpecDipolEast",    @"I_Begrenzt",
    @"IST_EHV#mainSpecDipolEast",    @"Warnung",
    @"IST_EHV#mainSpecDipolEast",    @"Fehler",
    @"IST_EHV#IECommon",    @"U_SOLL",
    @"IST_EHV#IECommon",    @"U_IST",
    @"IST_EHV#IECommon",    @"I_MAX",
    @"IST_EHV#IECommon",    @"I_IST",
    @"IST_EHV#IECommon",    @"Rampe",
    @"IST_EHV#IECommon",    @"I_Begrenzt",
    @"IST_EHV#IECommon",    @"Warnung",
    @"IST_EHV#IECommon",    @"Fehler",
    @"IST_EHV#preSpecVesel",    @"U_SOLL",
    @"IST_EHV#preSpecVesel",    @"U_IST",
    @"IST_EHV#preSpecVesel",    @"I_MAX",
    @"IST_EHV#preSpecVesel",    @"I_IST",
    @"IST_EHV#preSpecVesel",    @"Rampe",
    @"IST_EHV#preSpecVesel",    @"I_Begrenzt",
    @"IST_EHV#preSpecVesel",    @"Warnung",
    @"IST_EHV#preSpecVesel",    @"Fehler",
    @"IST_EHV#preSpecIE1",    @"U_SOLL",
    @"IST_EHV#preSpecIE1",    @"U_IST",
    @"IST_EHV#preSpecIE1",    @"I_MAX",
    @"IST_EHV#preSpecIE1",    @"I_IST",
    @"IST_EHV#preSpecIE1",    @"Rampe",
    @"IST_EHV#preSpecIE1",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE1",    @"Warnung",
    @"IST_EHV#preSpecIE1",    @"Fehler",
    @"IST_EHV#preSpecIE2",    @"U_SOLL",
    @"IST_EHV#preSpecIE2",    @"U_IST",
    @"IST_EHV#preSpecIE2",    @"I_MAX",
    @"IST_EHV#preSpecIE2",    @"I_IST",
    @"IST_EHV#preSpecIE2",    @"Rampe",
    @"IST_EHV#preSpecIE2",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE2",    @"Warnung",
    @"IST_EHV#preSpecIE2",    @"Fehler",
    @"IST_EHV#preSpecIE3",    @"U_SOLL",
    @"IST_EHV#preSpecIE3",    @"U_IST",
    @"IST_EHV#preSpecIE3",    @"I_MAX",
    @"IST_EHV#preSpecIE3",    @"I_IST",
    @"IST_EHV#preSpecIE3",    @"Rampe",
    @"IST_EHV#preSpecIE3",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE3",    @"Warnung",
    @"IST_EHV#preSpecIE3",    @"Fehler",
    @"IST_EHV#preSpecIE4",    @"U_SOLL",
    @"IST_EHV#preSpecIE4",    @"U_IST",
    @"IST_EHV#preSpecIE4",    @"I_MAX",
    @"IST_EHV#preSpecIE4",    @"I_IST",
    @"IST_EHV#preSpecIE4",    @"Rampe",
    @"IST_EHV#preSpecIE4",    @"I_Begrenzt",
    @"IST_EHV#preSpecIE4",    @"Warnung",
    @"IST_EHV#preSpecIE4",    @"Fehler",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Temperatur_1",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Temperatur_2",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Luftfeuchte",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Spannung",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Warnung",
    @"IST_cFP_STATUS#cFP35KVStatus",    @"Fehler",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Temperatur_1",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Temperatur_2",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Luftfeuchte",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Spannung",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Warnung",
    @"IST_cFP_STATUS#cFP65KVStatus",    @"Fehler",
    @"IST_cRIO_STATUS#ExpPC_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#ZEUS_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#ORCA_SollSet",    @"Zustand",
    @"IST_cRIO_STATUS#416Status_OK",    @"Zustand",
    @"IST_cRIO_STATUS#416HV_Freigabe",    @"Zustand",
    @"IST_cRIO_STATUS#416HV_aktiv",    @"Zustand",
    @"IST_cRIO_STATUS#436Status_OK",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_Freigabe",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_aktiv",    @"Zustand",
    @"IST_cRIO_STATUS#436VAO_AUF",    @"Zustand",
    @"IST_cRIO_STATUS#436HV_gekoppelt",    @"Zustand",
    @"IST_HV_RELAIS#Ost_Relais",    @"Zustand",
    @"IST_HV_RELAIS#West_Relais",    @"Zustand",
    @"IST_PXI_VOLTAGE#WestCh0",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh0",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh0",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh1",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh2",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh2",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh3",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh3",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh3",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh4",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh4",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh4",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh5",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh5",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh5",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh6",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh6",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh6",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh7",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh7",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh7",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh8",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh8",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh8",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh9",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh9",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh9",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh10",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh10",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh10",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh11",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh11",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh11",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh12",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh12",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh12",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh13",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh13",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh13",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh14",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh14",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh14",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh15",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh15",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh15",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh16",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh16",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh16",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh17",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh17",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh17",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh18",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh18",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh18",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh19",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh19",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh19",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh20",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh20",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh20",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh21",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh21",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh21",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh22",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh22",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh22",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#WestCh23",    @"U_IST",
    @"IST_PXI_VOLTAGE#WestCh23",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#WestCh23",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh0",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh0",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh0",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh1",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh2",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh2",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh3",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh3",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh3",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh4",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh4",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh4",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh5",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh5",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh5",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh6",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh6",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh6",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh7",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh7",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh7",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh8",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh8",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh8",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh9",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh9",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh9",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh10",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh10",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh10",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh11",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh11",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh11",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh12",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh12",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh12",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh13",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh13",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh13",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh14",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh14",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh14",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh15",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh15",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh15",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh16",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh16",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh16",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh17",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh17",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh17",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh18",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh18",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh18",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh19",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh19",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh19",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh20",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh20",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh20",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh21",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh21",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh21",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh22",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh22",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh22",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#EastCh23",    @"U_IST",
    @"IST_PXI_VOLTAGE#EastCh23",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#EastCh23",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#35KV_U",    @"U_IST",
    @"IST_PXI_VOLTAGE#35KV_U",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#35KV_U",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#65KV_U",    @"U_IST",
    @"IST_PXI_VOLTAGE#65KV_U",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#65KV_U",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"U_IST",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#KAL_U1",    @"Messung lauft",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"U_IST",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"Zeitstempel",
    @"IST_PXI_VOLTAGE#KAL_U2",    @"Messung lauft",
    @"IST_PXI_CHANNEL#WestCh0",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh0",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh0",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh0",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh0",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh1",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh1",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh1",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh1",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh1",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh2",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh2",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh2",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh2",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh2",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh3",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh3",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh3",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh3",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh3",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh4",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh4",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh4",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh4",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh4",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh5",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh5",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh5",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh5",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh5",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh6",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh6",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh6",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh6",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh6",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh7",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh7",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh7",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh7",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh7",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh8",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh8",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh8",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh8",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh8",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh9",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh9",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh9",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh9",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh9",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh10",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh10",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh10",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh10",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh10",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh11",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh11",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh11",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh11",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh11",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh12",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh12",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh12",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh12",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh12",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh13",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh13",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh13",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh13",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh13",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh14",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh14",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh14",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh14",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh14",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh15",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh15",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh15",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh15",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh15",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh16",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh16",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh16",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh16",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh16",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh17",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh17",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh17",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh17",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh17",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh18",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh18",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh18",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh18",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh18",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh19",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh19",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh19",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh19",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh19",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh20",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh20",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh20",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh20",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh20",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh21",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh21",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh21",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh21",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh21",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh22",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh22",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh22",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh22",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh22",    @"Fehler",
    @"IST_PXI_CHANNEL#WestCh23",    @"U_Soll",
    @"IST_PXI_CHANNEL#WestCh23",    @"U_IST",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_MAX",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_IST",
    @"IST_PXI_CHANNEL#WestCh23",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#WestCh23",    @"Warnung",
    @"IST_PXI_CHANNEL#WestCh23",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh0",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh0",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh0",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh0",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh0",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh1",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh1",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh1",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh1",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh1",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh2",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh2",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh2",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh2",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh2",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh3",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh3",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh3",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh3",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh3",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh4",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh4",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh4",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh4",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh4",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh5",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh5",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh5",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh5",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh5",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh6",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh6",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh6",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh6",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh6",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh7",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh7",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh7",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh7",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh7",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh8",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh8",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh8",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh8",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh8",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh9",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh9",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh9",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh9",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh9",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh10",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh10",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh10",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh10",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh10",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh11",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh11",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh11",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh11",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh11",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh12",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh12",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh12",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh12",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh12",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh13",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh13",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh13",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh13",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh13",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh14",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh14",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh14",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh14",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh14",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh15",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh15",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh15",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh15",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh15",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh16",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh16",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh16",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh16",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh16",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh17",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh17",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh17",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh17",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh17",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh18",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh18",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh18",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh18",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh18",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh19",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh19",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh19",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh19",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh19",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh20",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh20",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh20",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh20",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh20",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh21",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh21",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh21",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh21",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh21",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh22",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh22",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh22",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh22",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh22",    @"Fehler",
    @"IST_PXI_CHANNEL#EastCh23",    @"U_Soll",
    @"IST_PXI_CHANNEL#EastCh23",    @"U_IST",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_MAX",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_IST",
    @"IST_PXI_CHANNEL#EastCh23",    @"I_BEGRENZT",
    @"IST_PXI_CHANNEL#EastCh23",    @"Warnung",
    @"IST_PXI_CHANNEL#EastCh23",    @"Fehler",
    @"IST_EHV#postReg",    @"U_IST",
    @"IST_EHV#postRegInhibit",    @"Status",
    @"", @""
};

@interface ORHVcRIOModel (private)
- (void) timeout;
- (void) processNextCommandFromQueue;
@end

#define kBadHVcRIOValue -999
#define kHVcRIOPort 12340

@implementation ORHVcRIOModel

- (void) dealloc
{
    [setPointFile release];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [NSObject cancelPreviousPerformRequestsWithTarget:self];
    [buffer release];
	[cmdQueue release];
	[lastRequest release];
    [setPoints release];
    [measuredValues release];
    if([self isConnected]){
        [socket close];
        [socket setDelegate:nil];
        [socket release];
    }
	
    [ipAddress release];
	
	[super dealloc];
}

- (void) setUpImage
{
	[self setImage:[NSImage imageNamed:@"HVcRIO.tif"]];
}

- (void) makeMainController
{
	[self linkToController:@"ORHVcRIOController"];
}

#pragma mark ***Accessors
- (void) setSetPoint: (int)aIndex withValue: (float)value
{
    NSNumber* oldValue = [[setPoints objectAtIndex:aIndex] objectForKey:@"setPoint"];
    [[[self undoManager] prepareWithInvocationTarget:self] setSetPoint:aIndex withValue:[oldValue floatValue]];
    [[setPoints objectAtIndex:aIndex] setObject:[NSNumber numberWithFloat:value] forKey:@"setPoint"];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointChanged object:self];
}

- (void) setSetPointReadback: (int)aIndex withValue: (float)value
{
    NSString* oldValue = [[setPoints objectAtIndex:aIndex] objectForKey:@"readBack"];
    [[[self undoManager] prepareWithInvocationTarget:self] setSetPointReadback:aIndex withValue:[oldValue floatValue]];

    [[setPoints objectAtIndex:aIndex] setObject:[NSString stringWithFormat:@"%.3f",value] forKey:@"readBack"];

    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointChanged object:self];

}

- (void) setMeasuredValue: (int)aIndex withValue: (float)value
{
    [[measuredValues objectAtIndex:aIndex] setObject:[NSString stringWithFormat:@"%.3f",value] forKey:@"value"];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointChanged object:self];
    
}
- (void) createSetPointArray
{
    if(setPoints)[setPoints release];
    setPoints = [[NSMutableArray array] retain];
    int index = 0;
    for(;;) {
        NSMutableDictionary* dict = [NSMutableDictionary dictionary];
        [dict setObject:setPointList[index++]   forKey:@"item"];
        [dict setObject:setPointList[index++]   forKey:@"data"];
        [dict setObject:@"0"   forKey:@"setPoint"];
        [dict setObject:@"?" forKey:@"readBack"];
        [setPoints addObject:dict];
        if([setPointList[index] isEqualToString:@""])break;
    }
}

- (NSInteger) numSetPoints
{
    return [setPoints count];
}
- (void) createMeasuredValueArray
{
    if(measuredValues)[measuredValues release];
    measuredValues = [[NSMutableArray array] retain];
    int index = 0;
    for(;;) {
        NSMutableDictionary* dict = [NSMutableDictionary dictionary];
        [dict setObject:measuredValueList[index++]   forKey:@"item"];
        [dict setObject:measuredValueList[index++]   forKey:@"data"];
        [dict setObject:@"?" forKey:@"value"];
        [measuredValues addObject:dict];
        if([measuredValueList[index] isEqualToString:@""])break;
    }
}

- (NSInteger) numMeasuredValues
{
    return [measuredValues count];
}

- (void) setSetPoints:(NSMutableArray*)anArray
{
    [anArray retain];
    [setPoints release];
    setPoints = anArray;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointsChanged object:self];
}

- (void) setMeasuredValues:(NSMutableArray*)anArray
{
    [anArray retain];
    [measuredValues release];
    measuredValues = anArray;
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointsChanged object:self];
}
- (id) setPointAtIndex:(int)i
{
    if(i<[setPoints count]){
        return [[setPoints objectAtIndex:i] objectForKey:@"setPoint"];
    }
    else return nil;
}
- (id) setPointReadBackAtIndex:(int)i
{
    if(i<[setPoints count]){
        return [[setPoints objectAtIndex:i] objectForKey:@"readBack"];
    }
    else return nil;
}
- (id) setPointItem:(int)i forKey:(NSString*)aKey
{
    if(i<[setPoints count]){
        return [[setPoints objectAtIndex:i] objectForKey:aKey];
    }
    else return nil;
}

- (id) measuredValueItem:(int)i forKey:(NSString*)aKey
{
    if(i<[measuredValues count]){
        return [[measuredValues objectAtIndex:i] objectForKey:aKey];
    }
    else return nil;
}

- (id) measuredValueAtIndex:(int)i
{
    if(i<[measuredValues count]){
        return [[measuredValues objectAtIndex:i] objectForKey:@"value"];
    }
    else return nil;
}

- (NSString*) title
{
    return [NSString stringWithFormat:@"%@ (%@)",[self fullID],[self ipAddress]];
}

- (BOOL) wasConnected
{
    return wasConnected;
}

- (void) setWasConnected:(BOOL)aState
{
    wasConnected = aState;
}

- (NetSocket*) socket
{
	return socket;
}
- (void) setSocket:(NetSocket*)aSocket
{
	if(aSocket != socket)[socket close];
	[aSocket retain];
	[socket release];
	socket = aSocket;
    [socket setDelegate:self];
}

- (void) setIsConnected:(BOOL)aFlag
{
    isConnected = aFlag;
    [self setWasConnected:isConnected];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelIsConnectedChanged object:self];
}

- (void) connect
{
	if(!isConnected && [ipAddress length]){
        NSLog(@"%@: trying to connect\n",[self fullID]);
		[self setSocket:[NetSocket netsocketConnectedToHost:ipAddress port:kHVcRIOPort]];
        [self setIsConnected:[socket isConnected]];
	}
	else {
        NSLog(@"%@: trying to disconnect\n",[self fullID]);
		[self setSocket:nil];
        [self setIsConnected:[socket isConnected]];
	}
}

- (BOOL) isConnected
{
    return isConnected;
}

- (NSString*) ipAddress
{
    return ipAddress;
}

- (void) setIpAddress:(NSString*)aIpAddress
{
	if(!aIpAddress)aIpAddress = @"";
    [[[self undoManager] prepareWithInvocationTarget:self] setIpAddress:ipAddress];
    
    [ipAddress autorelease];
    ipAddress = [aIpAddress copy];
	
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelIpAddressChanged object:self];
}

- (void) netsocketConnected:(NetSocket*)inNetSocket
{
    if(inNetSocket == socket){
        [self setIsConnected:YES];
        NSLog(@"%@: Connected\n",[self fullID]);
        
        [cmdQueue removeAllObjects];
        [self setLastRequest:nil];
    }
}

- (BOOL) expertPCControlOnly    {return expertPCControlOnly;}
- (BOOL) zeusHasControl         {return zeusHasControl;}
- (BOOL) orcaHasControl         {return orcaHasControl;}

- (void) netsocket:(NetSocket*)inNetSocket dataAvailable:(unsigned)inAmount
{
    if(!lastRequest)return;
    
    if(inNetSocket == socket){
		NSString* theString = [[[[NSString alloc] initWithData:[inNetSocket readData] encoding:NSASCIIStringEncoding] autorelease] uppercaseString];
        
        [self parseString:theString];
    }
}

- (void) netsocketDisconnected:(NetSocket*)inNetSocket
{
    if(inNetSocket == socket){
        [self setIsConnected:NO];
        NSLog(@"%@: Disconnected\n",[self fullID]);
		[socket autorelease];
		socket = nil;
        [cmdQueue removeAllObjects];
        [self setLastRequest:nil];
    }
}

- (void) flushQueue
{
    [cmdQueue removeAllObjects];
    [self setLastRequest:nil];
    [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelQueCountChanged object: self];
}

- (void) parseString:(NSString*)theString
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(timeout) object:nil];
    
    theString = [theString trimSpacesFromEnds];
    theString = [theString lowercaseString];
    
    NSArray* lines = [theString componentsSeparatedByString:@"\n"];
    for(NSString* aLine in lines){
        if([aLine length]==0)       continue;
        
        if([lastRequest hasPrefix:@"write sp"]) {
            aLine = [aLine substringFromIndex:8];
            NSArray* theParts = [aLine componentsSeparatedByString:@","];
            int i;
            for(i=0;i<[theParts count];i++){
                float new = [[theParts objectAtIndex:i] floatValue];
                float old  =    [[[setPoints objectAtIndex:i] objectForKey:@"setPoint"] floatValue];
                float diff = fabsf([[theParts objectAtIndex:i] floatValue]-new);
                if(diff > 0.00001){
                    NSLog(@"HVcRIO WARNING: index %i: diff is not 0: %f ( abs(%f-%f)  \n",i,diff,new,old);
                }
             }
            [self setLastRequest:nil];
        }
        
        else if([lastRequest hasPrefix:@"read sp"]) {
            aLine = [aLine substringFromIndex:10];
            NSArray* theParts = [aLine componentsSeparatedByString:@","];
            int i=0;
            int maxIndex = [setPoints count];
            for(id aValue in theParts){
                [self setSetPointReadback:i withValue:[aValue floatValue]];
                i++;
                if(i>maxIndex) break;
            }
            [self setLastRequest:nil];
            [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointsChanged object: self];
        }
        
        else if([lastRequest hasPrefix:@"read mv"]) {
            aLine = [aLine substringFromIndex:10];
            NSArray* theParts = [aLine componentsSeparatedByString:@","];
            int i;
            for(i=0;i<[theParts count];i++){
                [self setMeasuredValue:i withValue:[[theParts objectAtIndex:i] floatValue]];
            }
            
            [self setLastRequest:nil];
            
            expertPCControlOnly = [[measuredValues objectAtIndex:146] boolValue];
            zeusHasControl      = [[measuredValues objectAtIndex:147] boolValue];
            orcaHasControl      = [[measuredValues objectAtIndex:148] boolValue];
            
            [[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelMeasuredValuesChanged object: self];
        }
        
        else if([lastRequest hasPrefix:@"select"]){//we await the command echo, but we don't await a response, so clear lastRequest after echo -tb-
            aLine = [aLine substringFromIndex:0];
            NSLog(@"   echo is:  %@ \n",aLine);
            [self setLastRequest:nil];
        }
    }
    [self processNextCommandFromQueue];
}

- (NSString*) setPointFile
{
    if(setPointFile==nil)return @"";
    else return setPointFile;
}

- (void) setSetPointFile:(NSString*)aPath
{
    [setPointFile autorelease];
    setPointFile = [aPath copy];
}

- (int) queCount
{
	return [cmdQueue count];
}

- (NSString*) lastRequest
{
	return lastRequest;
}

- (void) setLastRequest:(NSString*)aRequest
{
	[aRequest retain];
	[lastRequest release];
	lastRequest = aRequest;    
}
- (NSString*) commonScriptMethods
{
    NSArray* selectorArray = [NSArray arrayWithObjects:
                              @"writeSetpoints",
                              @"readBackSetpoints",
                              @"readMeasuredValues",
                              @"readSetPointsFile:(NSString*)",
                              @"setSetPoint:(int) withValue:(float)",
                              @"setPointAtIndex:(int)",
                              @"setPointReadBackAtIndex:(int)",
                              @"measuredValueAtIndex:(int)",

                              nil];
    
    return [selectorArray componentsJoinedByString:@"\n"];
}
#pragma mark ***Archival
- (id) initWithCoder:(NSCoder*)decoder
{
	self = [super initWithCoder:decoder];

	[[self undoManager] disableUndoRegistration];
    
	[self setWasConnected:      [decoder decodeBoolForKey:	 @"wasConnected"]];
    [self setIpAddress:         [decoder decodeObjectForKey: @"ORHVcRIOModelIpAddress"]];
    [self setSetPointFile:      [decoder decodeObjectForKey:@"setPointFile"]];
    [self setSetPoints:         [decoder decodeObjectForKey: @"setPoints"]];
    if(!setPoints)[self createSetPointArray];
    
    [self createMeasuredValueArray];
    
    if(wasConnected)[self connect];
    
	[[self undoManager] enableUndoRegistration];

	return self;
}

- (void) encodeWithCoder:(NSCoder*)encoder
{
    [super encodeWithCoder:encoder];
    [encoder encodeObject:setPointFile   forKey:@"setPointFile"];
    [encoder encodeBool:wasConnected	 forKey:@"wasConnected"];
    [encoder encodeObject:ipAddress      forKey:@"ORHVcRIOModelIpAddress"];
    [encoder encodeObject:setPoints      forKey:@"setPoints"];
}

#pragma mark *** Commands
- (void) writeSetpoints
{
    if([self isConnected]){
        NSMutableString* cmd = [NSMutableString stringWithString:@"write sp"];
        [cmd appendString:@":"];
        int i;
        int maxIndex = [setPoints count];
        for(i=0;i<maxIndex;i++){
            float valueToWrite = [[[setPoints objectAtIndex:i] objectForKey:@"setPoint"] floatValue];
            [cmd appendFormat:@"%f",valueToWrite];
            if(i != maxIndex-1)[cmd appendString:@","];
        }
        [self writeCmdString:cmd];
    }
}

- (void) readBackSetpoints
{
    if([self isConnected]){
        [self writeCmdString:@"read sp"];
    }
}

- (void) readMeasuredValues
{
    if([self isConnected]){
        [self writeCmdString:@"read mv"];
    }
}

- (void) writeCmdString:(NSString*)aCommand
{
	if(!cmdQueue)cmdQueue = [[ORSafeQueue alloc] init];
    if(![aCommand hasSuffix:@"\n"])aCommand = [NSString stringWithFormat:@"%@\n",aCommand];
	[cmdQueue enqueue:aCommand];
	[[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelQueCountChanged object: self];
	[self processNextCommandFromQueue];
}

- (void) readSetPointsFile:(NSString*) aPath
{
    [setPoints release];
    setPoints = [[NSMutableArray array] retain];
    
	[self setSetPointFile:aPath];
    NSMutableArray* anArray = [[NSArray arrayWithContentsOfFile:aPath]mutableCopy];
    [self setSetPoints: anArray];
    [anArray release];
	[[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelSetPointFileChanged object:self];
}

- (void) saveSetPointsFile:(NSString*) aPath
{
	NSString* fullFileName = [aPath stringByExpandingTildeInPath];
	NSString* s = [NSString stringWithFormat:@"%@",setPoints];
	[s writeToFile:fullFileName atomically:NO encoding:NSASCIIStringEncoding error:nil];
}
@end

@implementation ORHVcRIOModel (private)
- (void) timeout
{
	@synchronized (self){
		[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(timeout) object:nil];
		NSLogError(@"command timeout",@"HVcRIO",nil);
		[self setLastRequest:nil];
		[cmdQueue removeAllObjects]; //if we timeout we just flush the queue
		[[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelQueCountChanged object: self];
	}
}

- (void) processNextCommandFromQueue
{
    if(lastRequest)return;
	if([cmdQueue count] > 0){
		NSString* cmd = [cmdQueue dequeue];
		[[NSNotificationCenter defaultCenter] postNotificationName:ORHVcRIOModelQueCountChanged object: self];
        [self setLastRequest:cmd];
        [socket writeString:cmd encoding:NSASCIIStringEncoding];
        [self performSelector:@selector(timeout) withObject:nil afterDelay:100];//<----timeout !!!!!!!!!!!!!!!!!!!!
	}
}
@end
